FROM maven:3.9.6-eclipse-temurin-17 AS builder

# Copy source code
COPY . /app
WORKDIR /app

# Build the WAR file
RUN mvn clean install package -DskipTests

# Use Tomcat to run the app
FROM tomcat:9.0-jdk17

# Clean default apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy the WAR from the builder
COPY --from=builder /app/target/*.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
